SELECT
    R.*
FROM
    qryRoster R
WHERE
    [ROLE] = 'ATM'
    AND ISNULL(DOT_YYYYMM, '2099_12') >= FORMAT(DATEADD(MONTH, -1, GETDATE()), 'yyyy_MM')
    AND DOH_YYYYMM < FORMAT(GETDATE(), 'yyyy_MM')