SELECT
    a.NAME_REP,
    FNAME_REP,
    REP_EMAIL,
    RM_EMAIL,
    TERR_NM,
    F.BASE_BONUS,
    RM.[PLAN]
FROM
    qryRoster A
    LEFT JOIN tblRates_RM RM ON A.REGION_ID = RM.REGION_ID
    LEFT JOIN tblFCE_COMP F ON A.REP_EMAIL = F.FCE_EMAIL
WHERE
    a.[ROLE] = 'FCE'
    -- AND a.[isLATEST?] = 1
    AND ISNULL(DOT_YYYYMM, '2099_12') >= FORMAT(DATEADD(MONTH, -1, GETDATE()), 'yyyy_MM')
    AND TENNURE_MONTHS > 0;